### ISSUE TITLE
`file-name-matches-element`: TypeError: Cannot read properties of null (reading 'name')

### ISSUE THREAD

**Issue by silverwind** [github/eslint-plugin-custom-elements#57]
Linted Line:

```js
window.customElements.define('foo-bar', class extends HTMLElement {
```

Error:

```
TypeError: Cannot read properties of null (reading 'name')
Rule: "custom-elements/file-name-matches-element"
    at :matches(ClassDeclaration, ClassExpression)[superClass.name=/HTML.*Element/] (node_modules/eslint-plugin-custom-elements/lib/rules/file-name-matches-element.js:51:30)
    at ruleErrorHandler (node_modules/eslint/lib/linter/linter.js:1093:28)
    at node_modules/eslint/lib/linter/safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
    at Object.emit (node_modules/eslint/lib/linter/safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (node_modules/eslint/lib/linter/node-event-generator.js:297:26)
    at NodeEventGenerator.applySelectors (node_modules/eslint/lib/linter/node-event-generator.js:326:22)
    at NodeEventGenerator.enterNode (node_modules/eslint/lib/linter/node-event-generator.js:340:14)
    at CodePathAnalyzer.enterNode (node_modules/eslint/lib/linter/code-path-analysis/code-path-analyzer.js:795:23)
    at node_modules/eslint/lib/linter/linter.js:1128:32
```

**Comment by keithamus** [comment]
Thanks for the issue! I can get this fixed up next week unless you would like to contribute a fix?

It looks like we check the identifier node but a class expression in argument position doesn’t have one so it would need to be guarded with a `?`.

**Comment by silverwind** [comment]
I guess I can. So in this case, no name can be derived, so we skip rule basically for this file?

**Comment by silverwind** [comment]
Figured it out - https://github.com/github/eslint-plugin-custom-elements/pull/58
